### ISSUE TITLE
Installation via `local_install_dev_deps` fails when package is in subdirectory of GitHub repot

### ISSUE THREAD

**Issue by sebffischer** [r-lib/pak#385] opened 2022-05-02 14:47 UTC
I am trying to include `catboost` (Link: https://github.com/catboost/catboost/tree/master/catboost/R-package) into the *Remotes*  field of my R package `DESCRIPTION`  but when I run `pak::local_install_dev_deps(".")` I get the following error message: 

```
Error: No root directory found in /tmp/RtmpvTIdoX/X/catboost or its parent directories. Root criterion: contains a file "DESCRIPTION"
Type .Last.error.trace to see where the error occurred
```

To reproduce: 

1. Create empty package using `usethis::create_package(".")` in the package directory
2. Edit the DESCRIPTION file as below
3. run `pak::local_install_dev_deps(".")` from the package directory

```
Package: cat
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R:
    person("Sebastian", "Fischer", , "sebf.fischer@gmail.com", role = c("aut", "cre"),
           comment = c(ORCID = "YOUR-ORCID-ID"))
Description: What the package does (one paragraph).
License: MIT + file LICENSE
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
Imports:
  catboost
Remotes:
  catboost/catboost/catboost/R-package
RoxygenNote: 7.1.2
```

**Comment by gaborcsardi** [comment] 2022-05-03 08:26
Yeah, even just this fails:
```
❯ pak::pkg_install("catboost=catboost/catboost/catboost/R-package")

→ Will install 1 package.
→ The package (0 B) is cached.
+ catboost   1.0.5 👷‍♀️🔧 (GitHub: 09376bd)
ℹ No downloads are needed, 1 pkg is cached
ℹ Packaging catboost 1.0.5
Error: No root directory found in /private/var/folders/ph/fpcmzfd16rgbbk8mxvy9m2_h0000gn/T/Rtmp1hWl8C/X/catboost or its parent directories. Root criterion: contains a file "DESCRIPTION"
Type .Last.error.trace to see where the error occurred
```

**Comment by gaborcsardi** [comment] 2022-05-03 08:27
```
remotes::install_github("catboost=catboost/catboost/catboost/R-package")
```

seems to work, btw. if you need a workaround.

**Comment by sebffischer** [comment] 2022-05-03 17:15
Thanks! Is this an actual bug that will be addressed or am I simply misusing the pak function?

**Comment by gaborcsardi** [comment] 2022-05-03 17:58
Sure, it is a bug.

**Comment by sebffischer** [comment] 2022-09-23 19:50
I thought the latest pak update solved this, but I still get an error: 

``` r
pak::pkg_install("catboost=catboost/catboost/catboost/R-package")
#> 
#> ✔ Updated metadata database: 3.58 MB in 3 files.
#> ✔ Updated metadata database: 3.58 MB in 3 files.
#> 
#> ℹ Updating metadata database
#> ℹ Updating metadata database
#> ✔ Updating metadata database ... done
#> ✔ Updating metadata database ... done
#> 
#>  
#> 
#> → Will update 1 package.
#> → Will update 1 package.
#> → Will download 1 package with unknown size.
#> → Will download 1 package with unknown size.
#> + catboost 1.0.5 → 1.0.6 [bld][cmp][dl] (GitHub: 3d8891a)
#> + catboost 1.0.5 → 1.0.6 [bld][cmp][dl] (GitHub: 3d8891a)
#> ℹ Getting 1 pkg with unknown size
#> ℹ Getting 1 pkg with unknown size
#> ✔ Cached copy of catboost 1.0.6 (source) is the latest build
#> ✔ Cached copy of catboost 1.0.6 (source) is the latest build
#> ℹ Packaging catboost 1.0.6
#> ℹ Packaging catboost 1.0.6
#> Error: ! error in pak subprocess
#> Caused by error: 
#> ! No root directory found in /tmp/RtmpD0P4kA/X/catboost/catboost-catboost-3d8891a or its parent directories. Root criterion: contains a file "DESCRIPTION"
```

<sup>Created on 2022-09-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gaborcsardi** [comment] 2022-11-22 14:37
This is now fixed in pkgdepends: https://github.com/r-lib/pkgdepends/pull/290

This indeed works for me now:
```r
pak::pak_update(stream = "devel", force = TRUE)
pak::pkg_install("SparkR=github::apache/spark/R/pkg@v3.1.2?reinstall")
```

Btw. this is a duplicate of #374.

**Closed by gaborcsardi** 2022-11-22 14:37 UTC
Labels: bug
