### ISSUE TITLE
Failure to install package from github where `DESCRIPTION` is not in the root directory

### ISSUE THREAD

**Issue by grst** [r-lib/pak#398] opened 2022-06-29 10:34 UTC
the [mcp counter](https://github.com/ebecht/MCPcounter) package (for whatever reason) does not have the actual package in the root of the repository, but in the `Source` subdirectory. 

The following works fine with `remotes::install_github`: 

```
> remotes::install_github("ebecht/MCPcounter/Source")
```

However with `pak`, this fails: 

```console
>  pak::pkg_install("ebecht/MCPcounter/Source")
                                                                     
→ Will install 1 package.
→ Will download 1 package with unknown size.
+ MCPcounter   1.2.0 [bld][cmp][dl] (GitHub: b6eac73)
ℹ Getting 1 pkg with unknown size
✔ Cached copy of MCPcounter 1.2.0 (source) is the latest build
✔ No downloads needed, all packages are cached
ℹ Packaging MCPcounter 1.2.0
Error: No root directory found in /home/sturm/tmp/RtmpcskWxZ/X/MCPcounter or its parent directories. Root criterion: contains a file "DESCRIPTION"
Type .Last.error.trace to see where the error occurred
> .Last.error.trace

 Stack trace:

 12. (function (...)  ...
 13. base:::withCallingHandlers(cli_message = function(msg) { ...
 14. get("pkg_install_do_plan", asNamespace("pak"))(...)
 15. pkgdepends::install_package_plan(plan = plan, lib = lib, num_work ...
 16. base:::withCallingHandlers({ ...
 17. pkgdepends:::handle_events(state, events)
 18. pkgdepends:::handle_event(state, i)
 19. pkgdepends:::stop_task(state, worker)
 20. pkgdepends:::stop_task_package(state, worker)
 21. pkgdepends:::stop_task_package_uncompress(state, worker)
 22. pkgdepends:::start_task_package_build(state, worker$task)
 23. pkgdepends:::make_build_process(tree_dir, pkg, create_temp_dir(),  ...
 24. withr::with_libpaths(c(tmplib, lib), action = "prefix", pkgbuild_ ...
 25. base:::force(code)
 26. pkgbuild_process$new(path, tmp_dir, binary = binary, vignettes =  ...
 27. pkgbuild:::initialize(...)
 28. pkgbuild:::rcb_init(self, private, super, path, dest_path, binary ...
 29. pkgbuild:::build_setup(path, dest_path, binary, vignettes, manual ...
 30. pkgbuild:::pkg_path(path)
 31. rprojroot::find_root("DESCRIPTION", path)
 32. base:::stop("No root directory found in ", start_path, " or its p ...
 33. base:::.handleSimpleError(function (e)  ...
 34. h(simpleError(msg, call))
 35. base:::stop(e)
 36. (function (e)  ...

 x No root directory found in /home/sturm/tmp/RtmpcskWxZ/X/MCPcounter or its parent directories. Root criterion: contains a file "DESCRIPTION" 
```

### Version information

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS/LAPACK: /home/sturm/anaconda3/envs/immunedeconv_dev/lib/libopenblasp-r0.3.10.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] pak_0.3.0         ps_1.7.1          prettyunits_1.1.1 crayon_1.5.1     
 [5] withr_2.5.0       rprojroot_2.0.3   R6_2.5.1          cli_3.3.0        
 [9] curl_4.3.2        remotes_2.4.2     callr_3.7.0       tools_4.0.2      
[13] glue_1.6.2        compiler_4.0.2    processx_3.6.1    pkgbuild_1.3.1 
```

**Comment by gaborcsardi** [comment] 2022-06-29 18:18
This is a duplicate of https://github.com/r-lib/pak/issues/385

**Closed by gaborcsardi** 2022-06-29 18:18 UTC
