### ISSUE TITLE
pak seems to not understand `url` remotes

### ISSUE THREAD

**Issue by wch** [r-lib/pak#253] opened 2020-12-23 01:43 UTC
To work around #252, I tried using a `url` remote, as in:

```
  url::https://github.com/rstudio/bslib/archive/master.tar.gz
```

(https://github.com/rstudio/shiny/blob/83e10989056b07d3c25dd74a268fe7f3f641c884/DESCRIPTION#L121)

pak doesn't seem to understand it:

```
> pak::local_install_deps()
Error: Cannot install packages:
* deps::/Users/winston/Dropbox/Projects/shiny: Unknown remote type(s): `url`
```

**Comment by gaborcsardi** [comment] 2020-12-23 10:01
Duplicate of https://github.com/r-lib/pkgdepends/issues/10

**Closed by gaborcsardi** 2020-12-23 10:01 UTC
