### ISSUE TITLE
A way to ensure packages are built from source

### ISSUE THREAD

**Issue by psobolewskiPhD** [r-lib/pak#255] opened 2020-12-29 22:16 UTC
install.packages has the type="source" option.
I'd like a similar for pak to install packages from source only.
I'm running Apple Silicon M1 MacBook Pro and would like to try to ensure all packages are compiled natively in my natively compiled R.

**Comment by gaborcsardi** [comment] 2021-01-30 14:01
Duplicate of #237.

**Closed by gaborcsardi** 2021-01-30 14:01 UTC
Labels: feature
