### ISSUE TITLE
Failed to uncompress dev version of thematic on Windows

### ISSUE THREAD

**Issue by cderv** [r-lib/pak#268] opened 2021-02-08 10:18 UTC
`thematic` currently can't be installed from Github with **pak**

````r
> pak::pak_update()

Updating to version 0.1.2.9001

trying URL 'https://r-lib.github.io/p/pak/dev/bin/windows/contrib/4.0/pak_0.1.2.9001.zip'
Content type 'application/zip' length 13496539 bytes (12.9 MB)
downloaded 12.9 MB

files 'DESCRIPTION', 'Meta/package.rds' have the wrong MD5 checksums

Reloading pak.

> pak::pkg_install("rstudio/thematic")
                                                                            
> Will update 1 package.
> Will download 1 package with unknown size.
+ thematic 0.1.1 > 0.1.1.9000 [bld][cmp][dl] (GitHub: 03b8c7b)
? Do you want to continue (Y/n) Y
i Getting 1 pkg with unknown size
v Cached copy of thematic 0.1.1.9000 (source) is the latest build
v No downloads needed, all packages are cached          
i Packaging thematic 0.1.1.9000
x Failed to uncompress thematic 0.1.1.9000 (1.1s)                        
Error: Failed to uncompress 'thematic' from 'C:\\Users\\chris\\AppData\\Local\\Temp\\RtmpYTqiX7\\fileb54868391f8/src/contrib/thematic_0.1.1.9000_03b8c7b8e762a3a21c6aacbe71ea183433240182.tar.gz-tree'.
Type .Last.error.trace to see where the error occured
Run `rlang::last_error()` to see where the error occurred.

> .Last.error.trace

 Stack trace:

 12. (function (...)  ...
 13. base:::withCallingHandlers(cli_message = function(msg) { ...
 14. get("pkg_install_do_plan", asNamespace("pak"))(...)
 15. pkgdepends::install_package_plan(plan = plan, lib = lib, ...
 16. base:::withCallingHandlers({ ...
 17. pkgdepends:::handle_events(state, events)
 18. pkgdepends:::handle_event(state, i)
 19. pkgdepends:::stop_task(state, worker)
 20. pkgdepends:::stop_task_package(state, worker)
 21. pkgdepends:::stop_task_package_uncompress(state, worker)
 22. base:::throw(new_pkg_uncompress_error("Failed to uncompr ...
 23. base:::signalCondition(cond)
 24. (function (e)  ...
 25. base:::stop(e)
 26. (function (e)  ...

 x Failed to uncompress 'thematic' from 'C:\\Users\\chris\\AppData\\Local\\Temp\\RtmpYTqiX7\\fileb54868391f8/src/contrib/thematic_0.1.1.9000_03b8c7b8e762a3a21c6aacbe71ea183433240182.tar.gz-tree'. 
````

It installs correctly using `remotes::install_github("rstudio/thematic")`, so maybe there is something with **pak** ? 

As shown above, I updated **pak** before running the install.

````r
> sessioninfo::platform_info()
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  French_France.1252          
 ctype    French_France.1252          
 tz       Europe/Paris                
 date     2021-02-08   
````

**Comment by gaborcsardi** [comment] 2021-02-08 10:40
This is the Windows path length limit, pak uses slightly longer paths than remotes. It is a duplicate of #252.

**Closed by gaborcsardi** 2021-02-08 10:40 UTC
