### ISSUE TITLE
Install the latest release version from GitHub seems not work

### ISSUE THREAD

**Issue by eitsupi** [r-lib/pak#416] opened 2022-09-23 13:30 UTC
The documentation suggests that the latest release version can be installed in the same way as `remotes::install_github`, by specifying the following, but pak 0.3.1 seems to install HEAD.

```r
pak::pkg_install("tidyverse/dplyr@*release")
```

**Comment by tanho63** [comment] 2023-09-18 14:56
Stumbled on this today as well, digging to see if I can find out what the issue is (looks like it's in pkgdepends)

**Comment by gaborcsardi** [comment] 2023-09-18 14:57
Most probably, this was simply never implemented, contrary to the documentation. :(

**Comment by tanho63** [comment] 2023-09-18 17:17
Stumbled on this PR https://github.com/r-lib/pkgdepends/pull/321 by @pawelru while digging through pkgdepends, it looks like it adds the handling based on the existing PR-specific logic - could we reinvestigate that (obviously post-posit-conf?)

**Comment by gaborcsardi** [comment] 2023-09-20 12:34
That PR is merged, so it should be in the nightly pak build tomorrow.

**Closed by gaborcsardi** 2023-09-20 12:34 UTC

**Comment by tanho63** [comment] 2023-09-20 12:35
Thank you so much!
