### ISSUE TITLE
Error listing dev dependencies from `Config/Needs/*`

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/pak#332] opened 2021-11-18 15:21 UTC
I've run into a puzzling error where the pak isn't recognizing the ref spec in `Config/Needs/website`. The key is that I'm trying to install a package from an alternate repo, e.g. `gadenbuie/pkgdown` rather than `r-lib/pkgdown`.

Here's a small reprex DESCRIPTION file:

```r
withr::local_dir(withr::local_tempdir())
#> Setting deferred event(s) on global environment.
#>   * Execute (and clear) with `withr::deferred_run()`.
#>   * Clear (without executing) with `withr::deferred_clear()`.

desc <- desc::description$new("!new")
desc$set("Package", "demo")
desc$set("Imports", "remotes")
desc$set("Config/Needs/website", "gadenbuie/pkgdown, glue")
desc$write("DESCRIPTION")

cat(brio::read_file("DESCRIPTION"))
#> Package: demo
#> Title: {{ Title }}
#> Version: 1.0.0
#> Authors@R: 
#>     c(person(given = "Jo", family = "Doe", email = "jodoe@dom.ain",
#>       role = c("aut", "cre")))
#> Maintainer: {{ Maintainer }}
#> Description: {{ Description }}
#> License: {{ License }}
#> URL: {{ URL }}
#> BugReports: {{ BugReports }}
#> Encoding: UTF-8
#> Imports: remotes
#> Config/Needs/website: gadenbuie/pkgdown, glue
```

Calling `local_dev_deps()` for the website dependencies returns an empty `Cannot install packages:` error

```r
pak::local_dev_deps(".", dependencies = "Config/Needs/website")
#> Error: Cannot install packages:                                                 
#> 
#> Type .Last.error.trace to see where the error occurred
```

with the following trace

```r
.Last.error.trace
#> 
#>  Stack trace:
#> 
#>  12. (function (...)  ...
#>  13. base:::withCallingHandlers(cli_message = function(msg) { ...
#>  14. get("pkg_deps_internal", asNamespace("pak"))(...)
#>  15. pak:::pkg_deps_internal2(pkg, upgrade, dependencies)
#>  16. deps$stop_for_solution_error()
#>  17. private$plan$stop_for_solve_error()
#>  18. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
#>  19. base:::stop("Cannot install packages:\n", msg, call. = FALSE)
#>  20. base:::.handleSimpleError(function (e)  ...
#>  21. h(simpleError(msg, call))
#>  22. base:::stop(e)
#>  23. (function (e)  ...
#> 
#>  x Cannot install packages:
#>  
#> 
#> Warning message:
#> partial match of 'topenv' to 'topenvs' 
```

`remotes::dev_package_deps()` works as expected

```r
remotes::dev_package_deps(dependencies = "Config/Needs/website")
#> Needs update -----------------------------
#>  package installed    available    is_cran remote
#>  pkgdown 1.9000.90... 344a0d36a... FALSE   GitHub
```

and the reference isn't invalid since `pak` will also install the package as requested.

```r
pak::pak("gadenbuie/pkgdown")
#>                                                                              
#> → Will update 1 package.
#> → Will download 1 package with unknown size.
#> + pkgdown 1.9000.9000.9000 → 1.9000.9000.9000 👷🏾‍♀️🔧 ⬇ (GitHub: 344a0d3)
```

The error persists even after installing the requested version.

```r
sessioninfo::package_info("pkgdown")
#>  package     * version          date       lib source                            
#>  ...
#>  pkgdown       1.9000.9000.9000 2021-11-18 [1] Github (gadenbuie/pkgdown@344a0d3)
#>  ...
remotes::dev_package_deps(dependencies = "Config/Needs/website")
pak::local_dev_deps(dependencies = "Config/Needs/website")
#> Error: Cannot install packages:                                                 
#> 
#> Type .Last.error.trace to see where the error occurred
```

**Comment by gaborcsardi** [comment] 2021-11-18 15:25
I can't reproduce this, what is your OS?

```r
❯ pak::local_dev_deps(".", dependencies = "Config/Needs/website")
✔ Loading metadata database ... done
# A tibble: 58 × 31
   ref    type  direct directpkg status package version license needscompilation
   <chr>  <chr> <lgl>  <lgl>     <chr>  <chr>   <chr>   <chr>   <lgl>
 1 local… local TRUE   TRUE      OK     demo    1.0.0   {{ Lic… NA
 2 glue   stan… FALSE  FALSE     OK     glue    1.5.0   MIT + … FALSE
 3 gaden… gith… FALSE  FALSE     OK     pkgdown 1.9000… MIT + … TRUE
 4 R6     stan… FALSE  FALSE     OK     R6      2.5.1   MIT + … FALSE
 5 askpa… stan… FALSE  FALSE     OK     askpass 1.1     MIT + … FALSE
 6 base6… stan… FALSE  FALSE     OK     base64… 0.1-3   GPL-2 … FALSE
 7 brio   stan… FALSE  FALSE     OK     brio    1.1.2   MIT + … FALSE
 8 bslib  stan… FALSE  FALSE     OK     bslib   0.3.1   MIT + … FALSE
 9 cachem stan… FALSE  FALSE     OK     cachem  1.0.6   MIT + … FALSE
10 callr  stan… FALSE  FALSE     OK     callr   3.7.0   MIT + … FALSE
# … with 48 more rows, and 22 more variables: priority <chr>, md5sum <chr>,
#   sha256 <chr>, filesize <int>, built <chr>, platform <chr>, rversion <chr>,
#   repotype <chr>, repodir <chr>, target <chr>, deps <list>, mirror <chr>,
#   sources <list>, remote <list>, error <list>, metadata <list>,
#   dep_types <list>, params <list>, cache_status <chr>, lib_status <chr>,
#   old_version <chr>, new_version <chr>
```

**Comment by gadenbuie** [comment] 2021-11-18 17:02
This is weird! I did run `pak::pak_update(force = TRUE)` before creating the above reprex, but I also ran it now again ... and I can't reproduce the error any more locally -- but I still see the error in GHA.

When updating pak, both before posting the issue and after, I saw this output (and the byte count was identical) so I don't think my pak version is the issue.

```r
> pak::pak_update(force = TRUE)

Updating to version 0.1.2.9001

trying URL 'https://r-lib.github.io/p/pak/dev/bin/macosx/el-capitan/contrib/3.6/pak_0.1.2.9001.tgz'
Content type 'application/octet-stream' length 7393247 bytes (7.1 MB)
==================================================
downloaded 7.1 MB

* installing *binary* package ‘pak’ ...
* DONE (pak)

Reloading pak.
```

I'm on Mac OS, but I also saw the same issue [in GHA on `ubuntu-18`](https://github.com/rstudio/tblcheck/runs/4244669806?check_suite_focus=true#step:6:19), which kicked off this investigation.

```
> devtools::session_info()
─ Session info ──────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       OS X Snow Leopard 11.6      
 system   x86_64, darwin15.6.0   
```

Now I'm no longer seeing the issue locally, but I **am** still seeing the error [on GHA](https://github.com/rstudio/tblcheck/runs/4254303874?check_suite_focus=true#step:6:19). (In that example, I'm using `gadenbuie/pkgdown@tabset-allow-html`, which _is_ currently working for me locally.)

**Comment by gaborcsardi** [comment] 2021-11-18 17:14
This is probably https://github.com/r-lib/actions/issues/386

If it is then you can use the `pak1` branch of the `setup-dependencies` action as a workaround.

**Comment by gadenbuie** [comment] 2021-11-18 17:53
Thanks, but using `r-lib/actions/setup-r-dependencies@pak1` [gives the same error](https://github.com/rstudio/tblcheck/runs/4254931810?check_suite_focus=true#step:5:47).

**Comment by gaborcsardi** [comment] 2021-11-18 18:11
Oh, wait, in the `pkgdown/test` branch I can actually reproduce it.

**Comment by gaborcsardi** [comment] 2021-11-18 18:36
The issue is that you want `gadenbuie/pkgdown@tabset-allow-html` and `rstudio/quillt@tidytemplate` wants `r-lib/pkgdown`.

**Comment by gadenbuie** [comment] 2021-11-18 18:41
> The issue is that you want `gadenbuie/pkgdown@tabset-allow-html` and `rstudio/quillt@tidytemplate` wants `r-lib/pkgdown`.

ah that makes sense and makes it another example of r-lib/actions#386. Should this have been resolved with the `@pak1` version of `setup-r-dependencies`? Either way, I'm subscribed to r-lib/actions#386 so please feel free to close this issue if its tracked there.

**Comment by gaborcsardi** [comment] 2021-11-18 18:46
No, this is a different issue. It is a bug in the error reporting, i.e. pak should tell you that you requested two different versions for the same package, and this is not possible.

But the real error cannot be resolved. You need to decide if you want the `gadenbuie/pkgdown@tabset-allow-html` or the `r-lib/pkgdown` version of pkgdown.

**Comment by gadenbuie** [comment] 2021-11-18 18:54
> But the real error cannot be resolved. You need to decide if you want the `gadenbuie/pkgdown@tabset-allow-html` or the `r-lib/pkgdown` version of pkgdown.

Is there a way to make this decision via the DESCRIPTION file? I would have expected that explicitly declaring pkgdown in _my_ DESCRIPTION would take precedence over the pkgdown requested by quillt, provided that there isn't a version conflict.

**Comment by gaborcsardi** [comment] 2021-11-18 19:06
That would be dangerous, because it would always override the downstream dependency declarations (that you possibly don't know about and that can change over time).

There is no way to resolve this in pak yet. What you can do is forking `rstudio/quillt@tidytemplate` and changing the pkgdown requirement to match yours.

Alternatively, you can remove your `gadenbuie/pkgdown@tabset-allow-html` requirement, and install it in another step manully, after the `setup-dependencies` step.

**Comment by gadenbuie** [comment] 2021-11-18 19:09
Okay, thanks for explaining! For now I'll stick to installing the pkgdown I want in a separate step.

**Comment by gaborcsardi** [comment] 2021-11-26 12:36
This will be fixed by https://github.com/r-lib/pak/issues/336

**Closed by gaborcsardi** 2021-11-26 12:36 UTC
