### ISSUE TITLE
pacman::p_load for pak?

### ISSUE THREAD

**Issue by holgerbrandl** [r-lib/pak#594] opened 2024-02-17 21:15 UTC
With `pacman` package manager https://github.com/trinker/pacman one could easily load a package and it would install it if the library was yet missing locally:
```r
pacman::p_load(ggplot2)
ggplot(iris, aes(Sepal.Width, Sepal.Length)) + geom_point()
```
In the same spirit there was `pacman::p_load_gh("ricardo-bion/ggradar")` to optionally install and then load packages from github.

Could such a convenience function(s) be added to `pak` as well?

**Comment by gaborcsardi** [comment] 2024-02-18 08:11
This is a duplicate of #196, and I think don't think that this is a good idea, sorry.

**Closed by gaborcsardi** 2024-02-18 08:11 UTC
