### ISSUE TITLE
update the directly specified packages

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pak#118] opened 2019-04-11 20:33 UTC
need to elaborate....

**Comment by jennybc** [comment] 2019-04-11 20:42
If I use `pak::pkg_install("remotes")` as a drop-in substitute for `install.packages("remotes")`, it is surprising that my local version does NOT get upgraded to current CRAN version. It's surprising that I need to explicitly request that behaviour via `pak::pkg_install("remotes", upgrade = TRUE)`.

**Comment by ginolhac** [comment] 2019-05-03 12:34
sorry for a silly question, but to complete what @jennybc  wrote, what is the drop-in replacement for `update.packages()` ? I would imagine that `pak::pkg_install(upgrade = TRUE)` would do that.
But `pkg` cannot be empty. 
I see messages like `→ Will not update 57 packages.` But I cannot see how to actually perform the upgrades.

**Comment by jimhester** [comment] 2019-05-03 13:06
I think something like

```r
library(pak)
pkgs <- pak::lib_status()$package
pkg_install(pkgs, upgrade = TRUE)
```

Should update all your packages, including those from GitHub.

**Comment by ginolhac** [comment] 2019-05-03 13:25
thanks! Just tried and it seems to do something but no upgrade

```
 pak::pkg_install(pkgs, upgrade = TRUE)
ℹ Checking for package metadata updates
✔ All 5 metadata files are current.                                                                                                               
✔ Using session cached package metadata
✔ Using cached package metadata                                                                                                                   
 100  deps for  0/100                                                                                                                                                   
 10/260  100/260 
> 
```

tried, several times in Rstudio, same thing happening. In a fresh console outside Rstudio, it is a little different but still no upgrade

```
> pkg_install(pkgs, upgrade = TRUE)
ℹ Checking for package metadata updates
✔ Downloaded metadata files, 1.19 MB in 2 files.                                
✔ Updating metadata database                                                    
✔ Using cached package metadata                                                 
✔ 64 + 191 pkgs | kept 255, updated 0, new 0 | downloaded 0 (0 B) [22.7s]       
> 
```

**Comment by jennybc** [comment] 2019-05-09 16:31
I keep tripping over this, i.e. using `pak_install()` with the intention of "update to the current CRAN version" and then, downstream, realizing that I am still on some older version because I forgot to specify `upgrade = TRUE`.

**Comment by hadley** [comment] 2019-05-29 19:48
Duplicate of #108 — @jennybc until this is fixed, I think what you actually want is `pkg_install("cran::remotes")`

**Closed by hadley** 2019-05-29 19:48 UTC
