### ISSUE TITLE
Feature: specify version in pkg_install() and pak()

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/pak#356] opened 2022-01-13 08:18 UTC
Hi,

First, I wanted to say that this new `pak::pak()` approach is awesome, thanks and kudos!

In my experience, when I have to install a package, there can be 3 main locations:

1) it comes from the CRAN and I use `install.packages()`
2) it comes from GitHub and I use `remotes::install_github()`
3) it comes from CRAN Archives and I use `remotes::install_version()`

I wondered if installing a specific version would be within the scope of the package.

**Comment by gaborcsardi** [comment] 2022-01-13 08:24
This is a duplicate of https://github.com/r-lib/pak/issues/122

**Closed by gaborcsardi** 2022-01-13 08:24 UTC

**Comment by DanChaltiel** [comment] 2022-01-13 08:41
Oops, sorry, I promise I searched before though 😭

**Comment by gaborcsardi** [comment] 2022-01-13 09:36
No worries, the title of that issue wasn't right any more, so it was hard to find.
