### ISSUE TITLE
Error: callr subprocess failed

### ISSUE THREAD

**Issue by monovich** [r-lib/pak#175] opened 2020-07-09 23:13 UTC
`Error: callr subprocess failed: Failed to download RcppEigen from `https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/RcppEigen_0.3.3.7.0.tar.gz` and `https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/Archive/RcppEigen_0.3.3.7.0.tar.gz`.`

Essentially presents this error for every package attempted to download, four at a time per `pak` call. Manually installing package works perfectly. For reference, trying to install "pathfindR" with` pak::pkg_install("pathfindR") `

R - 4.0.2

**Comment by RichardJActon** [comment] 2020-07-17 16:18
I'm having the same issue

**Comment by jimhester** [comment] 2020-08-18 21:01
A reproducible example would be useful, but also I think this should already be fixed on the current master.

**Closed by jimhester** 2020-08-18 21:01 UTC
Labels: reprex

**Comment by mskyttner** [comment] 2020-12-13 16:57
I ran into this too. Here is a reprex. Use `docker build .` after saving a Dockerfile with this content:

```docker
FROM rocker/geospatial:4.0.3
RUN R -e 'remotes::install_cran("pak", dependencies = TRUE)'
RUN R -e 'pak::pkg_install("raquamaps/aquamapsdata@style-lint", ask = FALSE)'
```

This is the output I get:

```bash
Error: callr subprocess failed: Failed to download MASS from `https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/4.1.0/Recommended/MASS_7.3-53.tar.gz` and `https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/Archive/MASS_7.3-53.tar.gz`.
Failed to download Matrix from `https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/4.1.0/Recommended/Matrix_1.2-18.tar.gz` and `https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/Archive/Matrix_1.2-18.tar.gz`.
Failed to download RMySQL from `https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/RMySQL_0.10.20.tar.gz` and `https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/Archive/RMySQL_0.10.20.tar.gz`.
Failed to download duckdb from `https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/duckdb_0.2.2-1.tar.gz` and `https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/Archive/duckd
Execution halted
```

I tried using the latest pak from master (ie this line in the Dockerfile: `RUN R -e 'remotes::install_github("r-lib/pak@master", dependencies = TRUE)'` but couldn't install it due to another error message then:

```bash
Failed to install 'ps' from GitHub: Could not find tools necessary to compile a package Call `pkgbuild::check_build_tools(debug = TRUE)`
```
Not sure what build tool is required by ps that is not already in the rocker/geospatial image (I could find no system requirements listed in the DESCRIPTION for ps) and I couldn't run pkgbuild::check_build_tools since it didn't succeed to install.

Using remotes::install_github() instead of pak::install() works on the same stack.

**Comment by gaborcsardi** [comment] 2020-12-13 17:17
@mskyttner This is a closed issue. Install dev pak, like in the README, and if that fails, then open a new issue. Thanks.
